# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a305dd87a89cdfd35fa0a601e312f80459832986c7715511b132c9f1ceb8cca2b8d68037cc6452c7c7853a3ee40bcc35956cbb3df33561703044e508ec9953

test:
  secret_key_base: 3146c4365339b6f86ca69404dd3f8aa502dee13b8d5fde34fa6977066b4fe6a7f0904fccfd81ea49658d3ac1eecd7566f391ccc9a2e06c3f07c77d6876711385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
